name: EBF_AL
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.6.3
  - meme=5.3.0
  - deeptools=3.5.1
  - bedtools=2.30.0
  - seaborn=0.11.2
  - matplotlib=3.3.2
  - pandas=1.1.5
  - pybedtools=0.8.2
  - rich=10.7.0
  - gseapy=0.10.5
  - ipykernel=5.5.5
  - pyyaml=5.4.1
  - pygenometracks=3.3
  - tqdm=4.62.2
  - ucsc-wigtobigwig=377
  - cutadapt=2.10
