---
title: "GSE107242_norm counts"
author: "Aurelie Lenaerts"
date: "15/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## load libraries

```{r libraries, message=FALSE}
library("DESeq2")
library("ashr")
```

## Load and prepare data
Data from Li et al. 2018 
```{r count matrix, echo=FALSE}
genes.filtered <- read.delim("../data/genes.filtered.t2g", header=FALSE)
Li_rawcounts <- read.delim("../data/Li_rawcounts.tsv")
rownames(Li_rawcounts) <- Li_rawcounts[, "X"]
Li_rawcounts <- Li_rawcounts[, colnames(Li_rawcounts) != "X"]
colnames(Li_rawcounts) <- c("24h_1", "24h_2", "72h_1", "72h_2", "proB_1", "proB_2")
Li_rawcounts <- as.matrix(Li_rawcounts)
dim(Li_rawcounts)
```

Create samplesheet and rowdata.
```{r samplesheet}
samplesheet <- data.frame(sampleName = colnames(Li_rawcounts))
rownames(samplesheet) <- samplesheet$sampleName
state <- c(rep(0,length(samplesheet$sampleName)))
for (i in 1:length(state))
{
  state[i] <- substr(as.character(samplesheet$sampleName[i]),1,nchar(as.character(samplesheet$sampleName[i]))-2)
}
samplesheet$state <- state
samplesheet

length(unique(samplesheet$state))
stopifnot(all(rownames(samplesheet) == colnames(Li_rawcounts)))

rowdata <- data.frame(ENSEMBL = rownames(Li_rawcounts))
rowdata  = merge(rowdata, genes.filtered,
                            by.x = "ENSEMBL", by.y = "V2",
                            all.x = TRUE, all.y = FALSE, sort = FALSE)
rowdata <- rowdata[!duplicated(rowdata$ENSEMBL),]
```

Create variable of average counts across samples.
```{r avg_cond}
rowdata$max_avg_cond <- NA
for(i in 1:nrow(rowdata)){
  if(i %% 1000 == 0){
    cat(i, " ") # print gene index with a step of 1000
  }
  gene <- rowdata$ENSEMBL[i]
  conditions <- unique(samplesheet$state)
  avg_conds <- unlist(lapply(conditions, function(cond){
    mean(Li_rawcounts[rownames(Li_rawcounts) == gene, grepl(cond, colnames(Li_rawcounts))])
  }))
  rowdata$max_avg_cond[i] <- max(avg_conds)
}
```

Filter for genes with average counts greater than 100 and some data checks.
```{r filter}
avg_cond_thr <- 100
selected_genes <- rowdata$ENSEMBL[rowdata$max_avg_cond > avg_cond_thr]

Li_rawcounts = Li_rawcounts[order(rownames(Li_rawcounts)),]
rowdata = rowdata[order(rowdata$ENSEMBL),]
stopifnot(all(rowdata$ENSEMBL == rownames(Li_rawcounts)))
dim(Li_rawcounts)

Li_rawcounts <- Li_rawcounts[rownames(Li_rawcounts) %in% selected_genes, ]
rowdata <- rowdata[rowdata$ENSEMBL %in% selected_genes, ]
dim(Li_rawcounts)
stopifnot(all(rownames(Li_rawcounts) == rowdata$ENSEMBL))

rownames(Li_rawcounts) <- rowdata$V3

stopifnot(all(rownames(samplesheet) == colnames(Li_rawcounts)))
rownames(Li_rawcounts)[rownames(Li_rawcounts) == ""]
all(samplesheet$sampleName == colnames(Li_rawcounts))
```
We have 6 conditions and 10970 genes after the threshold

## Perform DEseq2 with filtered count data. 

```{r deseq}
dds <- DESeqDataSetFromMatrix(Li_rawcounts, samplesheet, design= ~ state, rowData = rowdata)
dds <- DESeq(dds)

dds$state
resultsNames(dds)
```

```{r normalised}
norm_counts <- counts(dds, normalized = TRUE)
norm_counts <- round(norm_counts, 1)
write.table(norm_counts, file = "../proc_data/Li_proB_norm_counts.tsv", quote = FALSE, sep = "\t")
```