---
title: "Ebf1 expr_public data"
author: "Aurelie Lenaerts"
date: "15/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## load libraries

```{r libraries, message=FALSE}
library("DESeq2")
```

## Load and prepare data

```{r count matrix, echo=FALSE}
HSC_MPP_rawcounts <- read.delim("../data/Sommerkamp_rawcounts.tsv")
CLP_GMP_rawcounts <- read.delim("../data/CLP_GMP_rawcounts.tsv")
genes.filtered <- read.delim("../data/genes.filtered.t2g", header=FALSE)
```

merge count matrix
```{r merge, echo=FALSE}
rawcount_matrix <- merge(HSC_MPP_rawcounts, CLP_GMP_rawcounts)
rownames(rawcount_matrix) <- rawcount_matrix[, "X"]
rawcount_matrix <- rawcount_matrix[, colnames(rawcount_matrix) != "X"]
rawcount_matrix <- as.matrix(rawcount_matrix)
dim(rawcount_matrix)
colnames(rawcount_matrix) <- c("HSCa", "HSCb", "HSCc", "HSCd", "MPP1a", "MPP1b", "MPP1c", "MPP1d", "MPP2a", "MPP2b", "MPP2c", "MPP2d", "MPP3a", "MPP3b", "MPP3c", "MPP3d","MPP4a", "MPP4b", "MPP4c", "MPP4d", "CLPa", "CLPb", "GMPa", "GMPb")
```

Create samplesheet and rowdata.
```{r samplesheet}
samplesheet <- data.frame(sampleName = colnames(rawcount_matrix))
rownames(samplesheet) <- samplesheet$sampleName
state <- c(rep(0,length(samplesheet$sampleName)))
for (i in 1:length(state))
{
  state[i] <- substr(as.character(samplesheet$sampleName[i]),1,nchar(as.character(samplesheet$sampleName[i]))-1)
}
samplesheet$state <- state
samplesheet
length(unique(samplesheet$state))
stopifnot(all(rownames(samplesheet) == colnames(rawcount_matrix)))

rowdata <- data.frame(ENSEMBL = rownames(rawcount_matrix))
rowdata = merge(rowdata, genes.filtered,
                by.x = "ENSEMBL", by.y = "V2",
                all.x = TRUE, all.y = FALSE, sort = FALSE)
rowdata <- rowdata[!duplicated(rowdata$ENSEMBL),]
```

Create variable of average counts across samples.
```{r avg_cond}
rowdata$max_avg_cond <- NA
for(i in 1:nrow(rowdata)){
  if(i %% 1000 == 0){
    cat(i, " ") # print gene index with a step of 1000
  }
  gene <- rowdata$ENSEMBL[i]
  conditions <- unique(samplesheet$state)
  avg_conds <- unlist(lapply(conditions, function(cond){
    mean(rawcount_matrix[rownames(rawcount_matrix) == gene, grepl(cond, colnames(rawcount_matrix))])
  }))
  rowdata$max_avg_cond[i] <- max(avg_conds)
}
```

Filter for genes with average counts greater than 100 and some data checks.
```{r filter}
avg_cond_thr <- 100
selected_genes <- rowdata$ENSEMBL[rowdata$max_avg_cond > avg_cond_thr]

rawcount_matrix = rawcount_matrix[order(rownames(rawcount_matrix)),]
rowdata = rowdata[order(rowdata$ENSEMBL),]
stopifnot(all(rowdata$ENSEMBL == rownames(rawcount_matrix)))
dim(rawcount_matrix)

rawcount_matrix_filtered <- rawcount_matrix[rownames(rawcount_matrix) %in% selected_genes, ]
rowdata_filtered <- rowdata[rowdata$ENSEMBL %in% selected_genes, ]
dim(rawcount_matrix_filtered)
stopifnot(all(rownames(rawcount_matrix_filtered) == rowdata_filtered$ENSEMBL))

rownames(rawcount_matrix_filtered) <- rowdata_filtered$V3

stopifnot(all(rownames(samplesheet) == colnames(rawcount_matrix_filtered)))
rownames(rawcount_matrix_filtered)[rownames(rawcount_matrix_filtered) == ""] 
```
# we have 24 conditions and 11762 genes after the threshold

## Perform DEseq2 with filtered count data. 

```{r deseq}
dds <- DESeqDataSetFromMatrix(rawcount_matrix_filtered, samplesheet, design= ~ state, rowData = rowdata_filtered)
dds <- DESeq(dds)
```

```{r normalised counts}
norm_counts <- counts(dds, normalized = TRUE)
norm_counts <- round(norm_counts, 1)
dim(norm_counts)
```

```{r plot Ebf1}
plotCounts(
  dds,
  'Ebf1',
  intgroup = "state",
  normalized = TRUE,)
write.table(norm_counts, file = "../proc_data/WT_prog_norm_counts.tsv", quote = FALSE, sep = "\t")
```
